         JOB        I19  SETUP  : "END OF FILE" ON UNIT  5 AFTER RECORD #  14
      12 SURFACE    W06 DATCRD  : Invalid/obsolete entry on 'DATA' keyword:        1; only valid option is 'ASOS' for ISHD data.
         JOB        I25   TEST  : SUMMARY: NO DATA EXTRACTION FOR UPPERAIR
         JOB        I25   TEST  : SUMMARY: NO DATA QA FOR UPPERAIR
         JOB        I26   TEST  : SUMMARY: NO DATA QA FOR SURFACE
         JOB        I27   TEST  : SUMMARY: NO DATA QA FOR ONSITE
         JOB        I27   TEST  : SUMMARY: NO ONSITE data to merge
             29 HEADERS PROCESSED FROM INPUT FILES
