       9 UPPERAIR   W04 LOCCRD  : Station elevation not allowed for UPPERAIR   pathway: input ignored!
      14 SURFACE    W06 DATCRD  : Invalid/obsolete entry on 'DATA' keyword:        1; only valid option is 'ASOS' for ISHD data.
       1 METPREP    W03 LOCCRD  : LOCATION keyword on METPREP pathway is OBSOLETE unless OSMIX and No UADATA;
       2 METPREP    W03 LOCCRD  :  The LOCATION used for sunrise in CBL calcs is from ONSITE (if available) or SURFACE station.
         JOB        I19  SETUP  : "END OF FILE" ON UNIT  5 AFTER RECORD #  20
         METPREP    I41 FNDCOMDT: ASOS commission date FOUND for WBAN =  14735; CALL4 = KALB; CALL3 = ALB; CommDate = 19950801
  880301 METPREP    I84  MPPBL  : Upper air sounding selected for this day: 12 Z
  880301 METPREP    I84  MPPBL  : UAID =   1 for HR:   7 LST
  880302 METPREP    I71  MPPBL  : Calm wind - No BL calculations for hour:  02
  880302 METPREP    I71  MPPBL  : Calm wind - No BL calculations for hour:  03
  880302 METPREP    I71  MPPBL  : Calm wind - No BL calculations for hour:  04
  880302 METPREP    I71  MPPBL  : Calm wind - No BL calculations for hour:  05
  880302 METPREP    I71  MPPBL  : Calm wind - No BL calculations for hour:  06
  880302 METPREP    I71  MPPBL  : Calm wind - No BL calculations for hour:  07
  880302 METPREP    I84  MPPBL  : Upper air sounding selected for this day: 12 Z
  880302 METPREP    I84  MPPBL  : UAID =   3 for HR:   7 LST
  880303 METPREP    I71  MPPBL  : Calm wind - No BL calculations for hour:  19
  880303 METPREP    I71  MPPBL  : Calm wind - No BL calculations for hour:  21
  880303 METPREP    I84  MPPBL  : Upper air sounding selected for this day: 12 Z
  880303 METPREP    I84  MPPBL  : UAID =   3 for HR:   7 LST
  880304 METPREP    I84  MPPBL  : Upper air sounding selected for this day: 12 Z
  880304 METPREP    I84  MPPBL  : UAID =   3 for HR:   7 LST
       4 METPREP    I79  FETCH  : EOF reached on input data file after 000000
