       9 UPPERAIR   W04 DATCRD  : Too many fields ( 4) on 'DATA' keyword! Block factor and type not used: BLKFAC=1, FTYPE=ASCII.
      15 UPPERAIR   W04 LOCCRD  : Station elevation not allowed for UPPERAIR   pathway: input ignored!
      21 SURFACE    W06 DATCRD  : Invalid/obsolete entry on 'DATA' keyword:        1; only valid option is 'ASOS' for ISHD data.
         JOB        I19  SETUP  : "END OF FILE" ON UNIT  5 AFTER RECORD #  29
         JOB        I27   TEST  : SUMMARY: NO DATA QA FOR ONSITE
         UPPERAIR   I30  UAEXT  : **** UPPER AIR EXTRACTION ****
         UPPERAIR   I39 GET620  : END-OF DATA WINDOW ENCOUNTERED
         UPPERAIR   I39  UAEXT  :  20 SOUNDINGS EXTRACTED
  880302 UPPERAIR   Q39 UAQASM  : UAWS MISSING FOR HR  07 AT LEVEL  8
  880302 UPPERAIR   Q39 UAQASM  : UAWS MISSING FOR HR  07 AT LEVEL  9
  880302 UPPERAIR   Q39 UAQASM  : UAWS MISSING FOR HR  07 AT LEVEL 10
  880304 UPPERAIR   Q37 REALQA  : LB: UALR=     -4.44 <      -2.00 FOR HR  19, LVL  08
  880306 UPPERAIR   Q38 REALQA  : UB: UALR=      5.71 >        5.00 FOR HR  07, LVL  02
  880306 UPPERAIR   Q38 REALQA  : UB: UALR=      5.06 >        5.00 FOR HR  07, LVL  03
  880309 UPPERAIR   Q37 REALQA  : LB: UALR=     -3.00 <      -2.00 FOR HR  19, LVL  02
  880310 UPPERAIR   Q38 REALQA  : UB: UALR=      5.90 >        5.00 FOR HR  07, LVL  09
         UPPERAIR   I39 UAQASM  : EOF AFTER UPPERAIR SOUNDING #    20
         SURFACE    I40  SFEXT  : *** SURFACE OBSERVATION EXTRACTION ***
         SURFACE    I41 FNDCOMDT: ASOS commission date FOUND for WBAN =  14735; CALL4 = KALB; CALL3 = ALB; CommDate = 19950801
         SURFACE    I49 GETSFC  : END-OF-DATA window encountered
         SURFACE    I49  SFEXT  :   240 SURFACE records extracted
  880302 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 02
  880302 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 03
  880302 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 04
  880302 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 05
  880302 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 06
  880302 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 07
  880303 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 19
  880303 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 21
  880306 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 00
  880306 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 01
  880306 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 02
  880306 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 03
  880306 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 04
  880306 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 05
  880306 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 06
  880306 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 07
  880308 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 21
  880308 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 22
  880309 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 00
  880309 SURFACE    CLM SFQASM  : CALM WINDS FOR HR 01
         SURFACE    I49 SFQASM  : END OF FILE AFTER HOURLY OBS #   240
