ifort mod_AsosCommDates.for   /compile_only /O2
ifort AERMET.FOR              /compile_only /O2
ifort AERSURF.FOR             /compile_only /O2
ifort AERSURF2.FOR            /compile_only /O2
ifort ASOSREC.FOR             /compile_only /O2
ifort AUDIT.FOR               /compile_only /O2
ifort AUTCHK.FOR              /compile_only /O2
ifort AVGCRD.FOR              /compile_only /O2
ifort BANNER.FOR              /compile_only /O2
ifort BULKRI.FOR              /compile_only /O2
ifort CALMS.FOR               /compile_only /O2
ifort CBLHT.FOR               /compile_only /O2
ifort CHRCRD.FOR              /compile_only /O2
ifort CHRCRD2.FOR             /compile_only /O2
ifort CHROND.FOR              /compile_only /O2
ifort CLHT.FOR                /compile_only /O2
ifort CLMCRD.FOR              /compile_only /O2
ifort CLOUDS.FOR              /compile_only /O2
ifort COMPDT.FOR              /compile_only /O2
ifort CUBIC.FOR               /compile_only /O2
ifort CVG.FOR                 /compile_only /O2
ifort D028LV.FOR              /compile_only /O2
ifort D144HD.FOR              /compile_only /O2
ifort D144LV.FOR              /compile_only /O2
ifort D3280H.FOR              /compile_only /O2
ifort D3280L.FOR              /compile_only /O2
ifort D6201H.FOR              /compile_only /O2
ifort D6201L.FOR              /compile_only /O2
ifort DATCRD.FOR              /compile_only /O2
ifort DATER.FOR               /compile_only /O2
ifort DEF256.FOR              /compile_only /O2
ifort DEFINE.FOR              /compile_only /O2
ifort DOCLDS.FOR              /compile_only /O2
ifort DTCRD.FOR               /compile_only /O2
ifort EQ_CCVR.FOR             /compile_only /O2
ifort ERRHDL.FOR              /compile_only /O2
ifort FDKEY.FOR               /compile_only /O2
ifort FDPATH.FOR              /compile_only /O2
ifort FETCH.FOR               /compile_only /O2
ifort FLIWK1.FOR              /compile_only /O2
ifort FLIWK2.FOR              /compile_only /O2
ifort FLOPEN.FOR              /compile_only /O2
ifort FLOS.FOR                /compile_only /O2
ifort FLSDG.FOR               /compile_only /O2
ifort FLSFC.FOR               /compile_only /O2
ifort FLWRK1.FOR              /compile_only /O2
ifort FLWRK2.FOR              /compile_only /O2
ifort FMTCRD.FOR              /compile_only /O2
ifort FNDCOMDT.FOR            /compile_only /O2
ifort GEO.FOR                 /compile_only /O2
ifort GET620.FOR              /compile_only /O2
ifort GETASOS.FOR             /compile_only /O2
ifort GETCCVR.FOR             /compile_only /O2
ifort GETFIL.FOR              /compile_only /O2
ifort GETFLD.FOR              /compile_only /O2
ifort GETFSL.FOR              /compile_only /O2
ifort GETSFC.FOR              /compile_only /O2
ifort GETTEMP.FOR             /compile_only /O2
ifort GETWRD.FOR              /compile_only /O2
ifort GMTLST.FOR              /compile_only /O2
ifort GREG.FOR                /compile_only /O2
ifort HDPROC.FOR              /compile_only /O2
ifort HEADER.FOR              /compile_only /O2
ifort HEAT.FOR                /compile_only /O2
ifort HGTCRD.FOR              /compile_only /O2
ifort HR0024.FOR              /compile_only /O2
ifort HTCALC.FOR              /compile_only /O2
ifort HTKEY.FOR               /compile_only /O2
ifort HUMID.FOR               /compile_only /O2
ifort HUSWX.FOR               /compile_only /O2
ifort ICHRND.FOR              /compile_only /O2
ifort INCRAD.FOR              /compile_only /O2
ifort INTEQA.FOR              /compile_only /O2
ifort INTHF.FOR               /compile_only /O2
ifort ISHWX.FOR               /compile_only /O2
ifort JBCARD.FOR              /compile_only /O2
ifort LATLON.FOR              /compile_only /O2
ifort LOCCRD.FOR              /compile_only /O2
ifort LWRUPR.FOR              /compile_only /O2
ifort MANDEL.FOR              /compile_only /O2
ifort MDCARD.FOR              /compile_only /O2
ifort MERGE.FOR               /compile_only /O2
ifort MIDNITE.FOR             /compile_only /O2
ifort MODEL.FOR               /compile_only /O2
ifort MPCARD.FOR              /compile_only /O2
ifort MPFIN.FOR               /compile_only /O2
ifort MPHEAD.FOR              /compile_only /O2
ifort MPMET.FOR               /compile_only /O2
ifort MPOUT.FOR               /compile_only /O2
ifort MPPBL.FOR               /compile_only /O2
ifort MPPROC.FOR              /compile_only /O2
ifort MPTEST.FOR              /compile_only /O2
ifort MRCARD.FOR              /compile_only /O2
ifort MRHDR.FOR               /compile_only /O2
ifort MRPATH.FOR              /compile_only /O2
ifort NETRAD.FOR              /compile_only /O2
ifort NR_ANG.FOR              /compile_only /O2
ifort NWSHGT.FOR              /compile_only /O2
ifort OAUDIT.FOR              /compile_only /O2
ifort OSCARD.FOR              /compile_only /O2
ifort OSCHK.FOR               /compile_only /O2
ifort OSDTCD.FOR              /compile_only /O2
ifort OSDUMP.FOR              /compile_only /O2
ifort OSFILL.FOR              /compile_only /O2
ifort OSFILL2.FOR             /compile_only /O2
ifort OSHRAV.FOR              /compile_only /O2
ifort OSNEXT.FOR              /compile_only /O2
ifort OSPATH.FOR              /compile_only /O2
ifort OSPRNT.FOR              /compile_only /O2
ifort OSQACK.FOR              /compile_only /O2
ifort OSQAST.FOR              /compile_only /O2
ifort OSRANGE.FOR             /compile_only /O2
ifort OSREAD.FOR              /compile_only /O2
ifort OSSMRY.FOR              /compile_only /O2
ifort OSSUMS.FOR              /compile_only /O2
ifort OSSWAP.FOR              /compile_only /O2
ifort OSTEST.FOR              /compile_only /O2
ifort OSTRA.FOR               /compile_only /O2
ifort OSWRTE.FOR              /compile_only /O2
ifort OTHHDR.FOR              /compile_only /O2
ifort P2MSUB.FOR              /compile_only /O2
ifort PRESET.FOR              /compile_only /O2
ifort PTAREA.FOR              /compile_only /O2
ifort PTGRAD.FOR              /compile_only /O2
ifort RDHUSW.FOR              /compile_only /O2
ifort RDISHD.FOR              /compile_only /O2
ifort RDLREC.FOR              /compile_only /O2
ifort RDSAMS.FOR              /compile_only /O2
ifort READRL.FOR              /compile_only /O2
ifort REALQA.FOR              /compile_only /O2
ifort RHOCAL.FOR              /compile_only /O2
ifort RNGCRD.FOR              /compile_only /O2
ifort SAMWX.FOR               /compile_only /O2
ifort SAUDIT.FOR              /compile_only /O2
ifort SBLHT.FOR               /compile_only /O2
ifort SCNGEN.FOR              /compile_only /O2
ifort SECCRD.FOR              /compile_only /O2
ifort SECCRD2.FOR             /compile_only /O2
ifort SETHUS.FOR              /compile_only /O2
ifort SETSAM.FOR              /compile_only /O2
ifort SETUP.FOR               /compile_only /O2
ifort SFCARD.FOR              /compile_only /O2
ifort SFCCH.FOR               /compile_only /O2
ifort SFCCH2.FOR              /compile_only /O2
ifort SFCCRD.FOR              /compile_only /O2
ifort SFCCRD2.FOR             /compile_only /O2
ifort SFCHK.FOR               /compile_only /O2
ifort SFCWXX.FOR              /compile_only /O2
ifort SFEXST.FOR              /compile_only /O2
ifort SFEXT.FOR               /compile_only /O2
ifort SFPATH.FOR              /compile_only /O2
ifort SFQASM.FOR              /compile_only /O2
ifort SFQAST.FOR              /compile_only /O2
ifort SFQATM.FOR              /compile_only /O2
ifort SFTRA.FOR               /compile_only /O2
ifort SMTHZI.FOR              /compile_only /O2
ifort STONUM.FOR              /compile_only /O2
ifort SUBST.FOR               /compile_only /O2
ifort SUMHF.FOR               /compile_only /O2
ifort SUMRY1.FOR              /compile_only /O2
ifort SUMRY2.FOR              /compile_only /O2
ifort SUNDAT.FOR              /compile_only /O2
ifort TDPEST.FOR              /compile_only /O2
ifort TEST.FOR                /compile_only /O2
ifort THRESH1MIN.FOR          /compile_only /O2
ifort UACARD.FOR              /compile_only /O2
ifort UACHK.FOR               /compile_only /O2
ifort UAEXST.FOR              /compile_only /O2
ifort UAEXT.FOR               /compile_only /O2
ifort UAMOVE.FOR              /compile_only /O2
ifort UAPATH.FOR              /compile_only /O2
ifort UAQASM.FOR              /compile_only /O2
ifort UAQAST.FOR              /compile_only /O2
ifort UATRA.FOR               /compile_only /O2
ifort UAUDIT.FOR              /compile_only /O2
ifort UAWNDW.FOR              /compile_only /O2
ifort UCALCO.FOR              /compile_only /O2
ifort UCALST.FOR              /compile_only /O2
ifort VALCRD.FOR              /compile_only /O2
ifort VARCRD.FOR              /compile_only /O2
ifort VRCARD.FOR              /compile_only /O2
ifort WRTCRD.FOR              /compile_only /O2
ifort YR2TOYR4.FOR            /compile_only /O2
ifort YR4TOYR2.FOR            /compile_only /O2
ifort XDTCRD.FOR              /compile_only /O2
ifort XTNDUA.FOR              /compile_only /O2
          
ifort /exe:aermet.exe  mod_AsosCommDates.obj AERMET.obj AERSURF.obj  AERSURF2.obj ASOSREC.obj AUDIT.obj  AUTCHK.obj  AVGCRD.obj  BANNER.obj  BULKRI.obj  CALMS.obj  CBLHT.obj  CHRCRD.obj ^
CHRCRD2.obj  CHROND.obj  CLHT.obj  CLMCRD.obj  CLOUDS.obj  COMPDT.obj  CUBIC.obj  CVG.obj  D028LV.obj  D144HD.obj  D144LV.obj  D3280H.obj ^
D3280L.obj  D6201H.obj  D6201L.obj  DATCRD.obj  DATER.obj  DEF256.obj  DEFINE.obj  DOCLDS.obj  DTCRD.obj  EQ_CCVR.obj  ERRHDL.obj  FDKEY.obj ^
FDPATH.obj  FETCH.obj  FLIWK1.obj  FLIWK2.obj  FLOPEN.obj  FLOS.obj  FLSDG.obj  FLSFC.obj  FLWRK1.obj  FLWRK2.obj  FNDCOMDT.obj FMTCRD.obj  ^
GEO.obj  GET620.obj  GETASOS.obj  GETCCVR.obj  GETFIL.obj  GETFLD.obj  GETFSL.obj  GETSFC.obj  GETTEMP.obj  GETWRD.obj  GMTLST.obj  GREG.obj  HDPROC.obj  HEADER.obj  HEAT.obj  ^
HGTCRD.obj  HR0024.obj  HTCALC.obj  HTKEY.obj  HUMID.obj  HUSWX.obj  ICHRND.obj  INCRAD.obj  INTEQA.obj  INTHF.obj  ISHWX.obj  JBCARD.obj  ^
LATLON.obj  LOCCRD.obj  LWRUPR.obj  MANDEL.obj  MDCARD.obj  MERGE.obj  MIDNITE.obj  MODEL.obj  MPCARD.obj  MPFIN.obj  MPHEAD.obj  MPMET.obj  ^
MPOUT.obj  MPPBL.obj  MPPROC.obj  MPTEST.obj  MRCARD.obj  MRHDR.obj  MRPATH.obj  NETRAD.obj  NR_ANG.obj  NWSHGT.obj  OAUDIT.obj  OSCARD.obj  ^
OSCHK.obj  OSDTCD.obj  OSDUMP.obj  OSFILL.obj  OSFILL2.obj  OSHRAV.obj  OSNEXT.obj  OSPATH.obj  OSPRNT.obj  OSQACK.obj  OSQAST.obj  OSRANGE.obj  OSREAD.obj  OSSMRY.obj  ^
OSSUMS.obj  OSSWAP.obj OSTEST.obj  OSTRA.obj  OSWRTE.obj  OTHHDR.obj  P2MSUB.obj  PRESET.obj  PTAREA.obj  PTGRAD.obj  RDHUSW.obj  RDISHD.obj  RDLREC.obj  ^
RDSAMS.obj  READRL.obj  REALQA.obj  RHOCAL.obj  RNGCRD.obj  SAMWX.obj  SAUDIT.obj  SBLHT.obj  SCNGEN.obj  SECCRD.obj  SECCRD2.obj  SETHUS.obj ^
SETSAM.obj  SETUP.obj  SFCARD.obj  SFCCH.obj  SFCCH2.obj  SFCCRD.obj  SFCCRD2.obj  SFCHK.obj  SFCWXX.obj  SFEXST.obj  SFEXT.obj  SFPATH.obj  ^
SFQASM.obj  SFQAST.obj  SFQATM.obj  SFTRA.obj  SMTHZI.obj  STONUM.obj  SUBST.obj  SUMHF.obj  SUMRY1.obj  SUMRY2.obj  SUNDAT.obj  TDPEST.obj ^
TEST.obj  THRESH1MIN.obj UACARD.obj  UACHK.obj  UAEXST.obj  UAEXT.obj  UAMOVE.obj  UAPATH.obj  UAQASM.obj  UAQAST.obj  UATRA.obj  UAUDIT.obj  UAWNDW.obj  ^
UCALCO.obj  UCALST.obj  VALCRD.obj  VARCRD.obj  VRCARD.obj  WRTCRD.obj  YR2TOYR4.obj  YR4TOYR2.obj  XDTCRD.obj  XTNDUA.obj

del *.obj